### ISSUE TITLE
Squash merge

### ISSUE THREAD

**Issue by jchristgit** [python-discord/king-arthur#263]
Why do we use squash merge in this repository?

I think we should apply similar strategy that we apply to the infra repository.

**Comment by jb3** [comment]
We don't, it appears as the default because it was the last used action and is
the one that's enabled. Nothing here is different to the infra repository.

There is a policy file for ff-bot on main so everything is already setup to be
able to `/merge` in the same way you would on infra.

PRs #243, #257, #261 and #264 were all merged using the fast-forward bot.

I've disabled all methods but squash merging now because:
- Merge commits are evil and obviously we have a policy of not using them on
  infra
- Rebase commits remove signed attestations of commit authority when done via
  GitHub, which rules them out for our use
- Squash merges, if we were to use a GitHub method, are probably the most useful
  as they retain a GPG attestation from the GitHub Web UI and have a use in
  places.

There is nothing else that needs to be done here for ff-bot to work, it is
already setup and as mentioned is being used.

**Comment by jb3** [comment]
Anything for my best-man!
